### ISSUE TITLE
Better implementation of Interceptors

### ISSUE THREAD

**Issue by TomFoyster** [SpoonX/aurelia-api#178] opened 2016-10-27 10:18 UTC
Having worked with Aurelia-API for a couple of months now, I'm finding dealing with the interceptors very restrictive. I know too that others have had issue with these, recently @rafaelcamargo has ran in to the same troubles as I. 

I understand that the interceptors used through Aurelia-API are actually just the interceptors originating in the Aurelia Fetch Client. However, as Aurelia-API is a wrapper for the Fetch Client, I feel that it should offer a better implementation of the interceptors. 

There is a couple of main issues;

The Response Interceptor doesn't allow access to the response body. The response body at the point the interceptor runs is a _ReadableStream_. This can be read by introducing an async promise to parse the JSON once the body has been recieved, but introducing this promise into the repsonse flow breaks the process. In my opinion - there should be a method available to intercept the response when it has completed, and before the result it passed back to the calling method. 

In a similar vein the request interceptor - it seems - offers no way of actually altering the request or its headers prior to the request being made. I had a use case where I needed to take a version from the request body (which was JSON) and add it to the If-Match header. As I couldn't do this through the interceptor I had to create my own wrapper, which wraps Aurelia-API, to set the headers prior to the request being made, and then unsets them afterwards. It really wasn't an ideal solution. 

I'd love to hear your thoughts on whether Aurelia-API can offer better, and actually useful, Interceptors.

**Comment by nexbit** [comment] 2016-10-27 10:59
@TomFoyster DISCLAIMER: I'm not an author of this library, but I know its code very well.

Actually, what you're describing are shortcomings of the `aurelia-fetch-client` library. The `aurelia-api` library does not manipulate `interceptors` in any way, it simply exposes the underlying `HttpClient` object from `aurelia-fetch-client`, and it is on that object that you configure your interceptors.
IMHO you should post an issue on that lib, as it's the only place where the issues you describe could be resolved.

**Comment by nexbit** [comment] 2016-10-27 11:08
> In a similar vein the request interceptor - it seems - offers no way of actually altering the request or its headers prior to the request being made. I had a use case where I needed to take a version from the request body (which was JSON) and add it to the If-Match header. As I couldn't do this through the interceptor I had to create my own wrapper, which wraps Aurelia-API, to set the headers prior to the request being made, and then unsets them afterwards. It really wasn't an ideal solution.

I can't tell anything about your first issue, I never wrote a response interceptor, but regarding your second one, I think it is already supported and widely used..
`aurelia-authentication` uses a request interceptor to add an `Authorization` header to every request (see https://github.com/SpoonX/aurelia-authentication/blob/master/src/fetchClientConfig.js). I never had the need to alter the request body, but I'm pretty sure it's supported too (in the end, you are returning a `Request` object from the interceptor, and nothing stops you from returning whatever you want).

**Comment by TomFoyster** [comment] 2016-10-27 11:27
Thanks for the response @nexbit. As I mention in my original description, I'm aware that the interceptors being used belong to the underlying `HttpClient` object. However I feel this should be a feature of the API plugin that possibly circumvents the `HttpClient` interceptors completely. This issue was created after being prompted by @doktordirk - so I'm presuming it's something they've thought of too. 

You make a good point about `aurelia-authentication` using interceptors to add in the Authentication token. It looks like it is possible to alter the headers in the request interceptor, however I still believe accessing the request body is an issue. Examining an example request object from the request interceptor, the properties available to me are; `bodyUsed`, `credentials`, `headers`, `integrity`, `method`, `mode`, `redirect`, `referrer`, `referrerPolicy`, and `url`. No reference to the physical body of the request.

Nothing stops you returning whatever you want from these interceptors, you're correct, but that's not really the issue being raised here.

**Comment by nexbit** [comment] 2016-10-27 11:39
You made some good points, but I'm under the impression that the root of the issue is related to the `Fetch` api specification.
The `Request` object is not something that `aurelia-fetch-client` provides, it simply comes from here: https://developer.mozilla.org/en-US/docs/Web/API/Request
If you need to support older browsers, you are probably using the `whatwg-fetch` polyfill, and so the `Request` class is implemented there.

What is available in an interceptor is not something we can control, in any of the involved libraries. So, if manipulating the request body is not supported by the current spec, we're simply out of luck.

Probably the same applies to your first issue re the response interceptor, but maybe there's something more in the [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) interface that can be used to provide a better experience.

**Comment by TomFoyster** [comment] 2016-10-27 11:54
You're right, the root of the issue is the Fetch API spec not allowing us access to either of these things in the request. That's why I've suggested it being a feature of `Aurelia-API`, as it's a wrapper for the fetch client it may be possible to acheive the desired functionality by working around the Fetch client, rather than directly working with it. 

Would like to hear the thoughts of the SpoonX guys, it might be that it's a non-starter anyway!

**Comment by doktordirk** [comment] 2016-10-27 12:27
background:
* aurelia-fetch-client should have been immutable and transient (as they admitted)
* that'll be kinda problem for aurelia-authentication since it adds interceptors
* generally i was more thinking of easing the use of additional interceptors for authentication since that could cleanup  the mess with all those token response formats
* as for working with the body: generally the rest! server should provide properly formatted responses. 

given that, one can currently add interceptors either later or with a configuration function. however, the former doesn't treat the client as immutable and the latter is a nuisance since configuration by object is much easier. hence, i see the need to allow referencing interceptors in the config object to aurelia-api

as for working with the body. yeah, that's really more an aurelia-fetch-client issue. though it would make things easier if aurelia-api would not automatically call .json() on an already read stream. hence, i think we should add a check for that

**Comment by nexbit** [comment] 2016-10-27 17:22
Maybe we could add chainable pre-request handlers, and post-response ones. 

For example, the issue https://github.com/SpoonX/aurelia-api/issues/166 could be resolved by moving the `json` conversion to a post-response handler (or filter, or pipeline step, whatever we want it named), that in turn could be added or not to user discretion. Or for BC added by default, but one can simply reset the handlers and add whatever he/she wants.

**Comment by nexbit** [comment] 2016-10-27 17:42
Just to be clear, what I mean is to avoid interceptors completely, and build an internal promise-based pipeline, so that we have everything under control and we're not dependant on the underlying fetch spec.

**Comment by doktordirk** [comment] 2016-11-10 10:28
the interceptors are aurelia specific. not using them would essentially just duplicate that mechanism

**Comment by guidorice** [comment] 2016-11-11 19:37
I agree with the subject of this issue, but a more critical question for me is: how DO you configure the fetch client's interceptor with aurelia-api?  I just noticed my interceptor and default http headers stopped working when I ported my project over to using aurelia-api. Originally in`app.js` I simply DI injected the Fetch HttpClient and then 
```
myFetchClient.configure( config => { 
 config.withDefaults(...setup http headers here...);
 config.withInterceptor(...setup error handling here...);
});
```
I did this in `app.js` so I could puts errors in a singleton errors/warnings model for display in the UI. The above stopped working after I ported my project to aurelia-api.  Is it using a sandboxed version of fetch client or something?

There is this section from aurelia-cli docs but dont understand the critical part: how to invoke withDefaults() and withInterceptor():
> As mentioned in the introduction, aurelia-api uses aurelia-fetch-client. If you wish to bypass the aurelia-api layer of configuration, simply supply a callback. The callback will receive the original configure instance. 

Hopefully I am overlooking something easy. Don't want to have to roll back my aurelia-api implementation because it is really convenient - it does bring a lot to the table.

**Comment by doktordirk** [comment] 2016-11-11 20:23
it's a fluent api,. so either

```js
 config.withDefaults(...setup http headers here...)
     .withInterceptor(...setup error handling here...);
```
or at any point 
`client.interceptors.push(myInterceptor)`

**Comment by guidorice** [comment] 2016-11-11 20:43
@doktordirk thanks very much - I was attempting to configure the httpclient directly which seem to have been destructive. Like you suggest, this worked
```
import {Config} from 'aurelia-api';
...
let client = this.config.endpoints.[myendpoint].client;
client.interceptors.push({...})
```

**Comment by RWOverdijk** [comment] 2018-10-11 13:28
Closing this for now. If this is still relevant, feel free to reopen the issue.

Note: this is a copy-paste comment to clean up the issues. It's not personal, and I didn't review the issue before posting this. They're all outdated and I need a way to figure out what's still relevant.

Thank you for understanding :)

**Closed by RWOverdijk** 2018-10-11 13:28 UTC
